/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoluntariadoRouteImport } from './routes/voluntariado'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PrecisaDeAjudaRouteImport } from './routes/precisa-de-ajuda'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MissaoRouteImport } from './routes/missao'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ComoContribuirRouteImport } from './routes/como-contribuir'
import { Route as IndexRouteImport } from './routes/index'

const VoluntariadoRoute = VoluntariadoRouteImport.update({
  id: '/voluntariado',
  path: '/voluntariado',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecisaDeAjudaRoute = PrecisaDeAjudaRouteImport.update({
  id: '/precisa-de-ajuda',
  path: '/precisa-de-ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoRoute = MissaoRouteImport.update({
  id: '/missao',
  path: '/missao',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoContribuirRoute = ComoContribuirRouteImport.update({
  id: '/como-contribuir',
  path: '/como-contribuir',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-contribuir': typeof ComoContribuirRoute
  '/contactos': typeof ContactosRoute
  '/missao': typeof MissaoRoute
  '/noticias': typeof NoticiasRoute
  '/precisa-de-ajuda': typeof PrecisaDeAjudaRoute
  '/quem-somos': typeof QuemSomosRoute
  '/voluntariado': typeof VoluntariadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-contribuir': typeof ComoContribuirRoute
  '/contactos': typeof ContactosRoute
  '/missao': typeof MissaoRoute
  '/noticias': typeof NoticiasRoute
  '/precisa-de-ajuda': typeof PrecisaDeAjudaRoute
  '/quem-somos': typeof QuemSomosRoute
  '/voluntariado': typeof VoluntariadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-contribuir': typeof ComoContribuirRoute
  '/contactos': typeof ContactosRoute
  '/missao': typeof MissaoRoute
  '/noticias': typeof NoticiasRoute
  '/precisa-de-ajuda': typeof PrecisaDeAjudaRoute
  '/quem-somos': typeof QuemSomosRoute
  '/voluntariado': typeof VoluntariadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-contribuir'
    | '/contactos'
    | '/missao'
    | '/noticias'
    | '/precisa-de-ajuda'
    | '/quem-somos'
    | '/voluntariado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-contribuir'
    | '/contactos'
    | '/missao'
    | '/noticias'
    | '/precisa-de-ajuda'
    | '/quem-somos'
    | '/voluntariado'
  id:
    | '__root__'
    | '/'
    | '/como-contribuir'
    | '/contactos'
    | '/missao'
    | '/noticias'
    | '/precisa-de-ajuda'
    | '/quem-somos'
    | '/voluntariado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoContribuirRoute: typeof ComoContribuirRoute
  ContactosRoute: typeof ContactosRoute
  MissaoRoute: typeof MissaoRoute
  NoticiasRoute: typeof NoticiasRoute
  PrecisaDeAjudaRoute: typeof PrecisaDeAjudaRoute
  QuemSomosRoute: typeof QuemSomosRoute
  VoluntariadoRoute: typeof VoluntariadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voluntariado': {
      id: '/voluntariado'
      path: '/voluntariado'
      fullPath: '/voluntariado'
      preLoaderRoute: typeof VoluntariadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precisa-de-ajuda': {
      id: '/precisa-de-ajuda'
      path: '/precisa-de-ajuda'
      fullPath: '/precisa-de-ajuda'
      preLoaderRoute: typeof PrecisaDeAjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao': {
      id: '/missao'
      path: '/missao'
      fullPath: '/missao'
      preLoaderRoute: typeof MissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-contribuir': {
      id: '/como-contribuir'
      path: '/como-contribuir'
      fullPath: '/como-contribuir'
      preLoaderRoute: typeof ComoContribuirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoContribuirRoute: ComoContribuirRoute,
  ContactosRoute: ContactosRoute,
  MissaoRoute: MissaoRoute,
  NoticiasRoute: NoticiasRoute,
  PrecisaDeAjudaRoute: PrecisaDeAjudaRoute,
  QuemSomosRoute: QuemSomosRoute,
  VoluntariadoRoute: VoluntariadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
